//==================================================
// This file contains the Excluded objects
// Generated By User: winnimui
// Format Version: 2
// Date: Fri May 12 09:54:36 2023
// ExclMode: default
//==================================================
CHECKSUM: "3370808172 3187071460"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_core.ublpwm_gen
ANNOTATION: " Legacy code, compared againest Mero"
Block 161 "1104666086" "do_db_reg_update = 1'b0;"
ANNOTATION: " Legacy code, compared againest Mero"
Block 402 "2338675172" "bl_on <= 1'b1;"
ANNOTATION: "Legacy code, compared againest Mero"
Block 168 "4211881408" "next_db_reg_update_state = 2'b1;"
ANNOTATION: "Legacy code, compared againest Mero"
Block 294 "1655083149" "next_bl_state = s_BLPWM_DISABLED;"
ANNOTATION: "compared vs Mero, it was covered by rbbmif_client_dcio_test which is part of dmu_sim_regress"
Block 198 "519086769" "next_update_bl_active_duty_cycle_int = {15'b0, reg_BL_ACTIVE_INT_FRAC_CNT[15]};"
ANNOTATION: "Legacy code, compared againest Mero, in Mero it is covered by rbbmif_client_dcio_test which is part of dmu_sim_regress"
Block 217 "4156787447" "next_update_bl_active_duty_cycle_frac = {reg_BL_ACTIVE_INT_FRAC_CNT[14:0], 1'b0};"
ANNOTATION: "will not get hit as all cases are defined"
Block 281 "3996536863" "dbg_sclk_count <= 2'b0;"
ANNOTATION: "input_refclk_sel feature deprecated, only default 0 used"
Block 275 "1810716082" "if ((dbg_sclk_count == 2'b1))"
ANNOTATION: "input_refclk_sel feature deprecated, only default 0 used"
Block 280 "887442390" "dbg_sclk_count <= (dbg_sclk_count + 2'b1);"
ANNOTATION: "input_refclk_sel feature deprecated, only default 0 used"
Block 279 "3536352023" "dbg_sclk_count <= 2'b0;"
ANNOTATION: "input_refclk_sel feature deprecated, only default 0 used"
Block 278 "3303044882" "if ((dbg_sclk_count == 2'b11))"
ANNOTATION: "input_refclk_sel feature deprecated, only default 0 used"
Block 277 "3584053042" "dbg_sclk_count <= 2'b1;"
ANNOTATION: "input_refclk_sel feature deprecated, only default 0 used"
Block 276 "779737077" "dbg_sclk_count <= 2'b0;"
CHECKSUM: "3370808172 990882207"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_core.ublpwm_gen
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 next_active_duty_cycle_cnt_frac_carry "net next_active_duty_cycle_cnt_frac_carry"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 next_active_duty_cycle_cnt_frac [16] "net next_active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 next_active_duty_cycle_cnt_frac [12] "net next_active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 next_active_duty_cycle_cnt_frac [10] "net next_active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle next_active_duty_cycle_cnt_frac [0] "net next_active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle next_active_duty_cycle_cnt_frac [1] "net next_active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle next_active_duty_cycle_cnt_frac [2] "net next_active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle next_active_duty_cycle_cnt_frac [3] "net next_active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle next_active_duty_cycle_cnt_frac [4] "net next_active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [5] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [6] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [7] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [8] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [9] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [10] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [11] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [12] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [13] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [14] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [15] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle active_duty_cycle_cnt_frac [16] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle active_duty_cycle_cnt_frac [0] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle active_duty_cycle_cnt_frac [1] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle active_duty_cycle_cnt_frac [2] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle active_duty_cycle_cnt_frac [3] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle active_duty_cycle_cnt_frac [4] "reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle next_update_bl_active_duty_cycle_frac_flopped [0] "reg next_update_bl_active_duty_cycle_frac_flopped[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle next_update_bl_active_duty_cycle_frac [0] "reg next_update_bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [5] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [6] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [7] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [8] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [9] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [10] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [11] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [12] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [13] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [14] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [15] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle bl_active_duty_cycle_frac [0] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle bl_active_duty_cycle_frac [1] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle bl_active_duty_cycle_frac [2] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle bl_active_duty_cycle_frac [3] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle bl_active_duty_cycle_frac [4] "reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " tied to 4'b1111 "
Toggle iREGS_be "net iREGS_be[3:0]"
ANNOTATION: " default value is 0 "
Toggle 1to0 irf_BL_PWM_GRP1_READBACK_DB_REG_VALUE_EN "net irf_BL_PWM_GRP1_READBACK_DB_REG_VALUE_EN"
CHECKSUM: "3370808172 3846472135"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_core.ublpwm_gen
Fsm bl_state "3015518728"
ANNOTATION: " needs a reset in the middle of sequence, can be tested if DV tests get improved but not required "
Transition s_BLPWM_WAIT_FOR_1ST_REFCLK->s_BLPWM_DISABLED "2->0"
Fsm bl_state "3015518728"
ANNOTATION: " needs a reset in the middle of sequence, can be tested if DV tests get improved but not required "
Transition s_BLPWM_JUST_ENABLED->s_BLPWM_DISABLED "1->0"
Fsm db_reg_update_state "4098030394"
ANNOTATION: " BL_PWM_GRP1_UPDATE_AT_FRAME_START should not change while pending is asserted. "
Transition s_db_POST_FS_UPDATE_AT_END_BL_PERIOD->'h0 "3->0"
Fsm db_reg_update_state "4098030394"
ANNOTATION: " needs a reset in the middle of sequence, can be tested if DV tests get improved but not required "
Transition s_db_POST_FRAME_START_DELAY->'h0 "2->0"
CHECKSUM: "3370808172 1168085257"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_core.ublpwm_gen
ANNOTATION: " DBG_BL_PWM_INPUT_REFCLK_SELECT register is obsolete feature, confirmed as well by software team "
Condition 69 "1826709312" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1)) 1 -1" (1 "01")
ANNOTATION: " DBG_BL_PWM_INPUT_REFCLK_SELECT register is obsolete feature, confirmed as well by software team "
Condition 52 "1088840078" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1)) 1 -1" (1 "01")
ANNOTATION: " DBG_BL_PWM_INPUT_REFCLK_SELECT register is obsolete feature, confirmed as well by software team "
Condition 46 "3458347982" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1)) 1 -1" (1 "01")
ANNOTATION: " DBG_BL_PWM_INPUT_REFCLK_SELECT register is obsolete feature, confirmed as well by software team  "
Condition 38 "3026573180" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT == 2'b0) && (iREF_CLK == 1'b1)) 1 -1" (1 "01")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 60 "2138000859" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (2 "01")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 60 "2138000859" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 59 "3920987006" "((irf_BL_PWM_GRP1_REG_LOCK == 1'b0) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1))) 1 -1" (2 "10")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 47 "2937502913" "((do_db_reg_update == 1'b1) && (bl_pwm_ref_cnt == reg_BL_PWM_REF_DIV) && (dbg_bl_pwm_just_enabled_waiting_for_first_refclk != 1'b1)) 1 -1" (3 "110")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 25 "1617060809" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
ANNOTATION: "  legacy code, did not get covered in the past. Also hard to hit this test, in order to hit this case it should already have received frame_start and while waiting for other events to happen, goes back to state 00 "
Condition 23 "939127057" "((irf_BL_PWM_GRP1_UPDATE_AT_FRAME_START == 1'b1) && (frame_start_already_received == 1'b0)) 1 -1" (2 "10")
ANNOTATION: "  legacy not covered, also condition is not possible "
Condition 21 "626146691" "((irf_BL_PWM_EN == 1'b1) && (BL_PWM_EN_rising_edge == 1'b1) && irf_BL_PWM_EN_EQ_ZERO) 1 -1" (1 "011")
ANNOTATION: "  Legacy code, compared againest Mero  "
Condition 17 "1904493209" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (2 "01")
ANNOTATION: "  Legacy code, compared againest Mero  "
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (4 "111")
ANNOTATION: " Legacy code, compared againest Mero "
Condition 13 "1662645362" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (2 "01")
ANNOTATION: " Legacy code "
Condition 12 "2860523178" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
ANNOTATION: " Legacy code "
Condition 12 "2860523178" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
ANNOTATION: " Legacy code "
Condition 12 "2860523178" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (1 "011")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 24 "2067887941" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 24 "2067887941" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 17 "1904493209" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (3 "10")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 17 "1904493209" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (1 "011")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 8 "3761564516" "((disp_capture_start_sclk_flopped == 1'b1) && (db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (4 "1110")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 8 "3761564516" "((disp_capture_start_sclk_flopped == 1'b1) && (db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "1101")
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1"
Condition 15 "2955745314" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
Condition 14 "3460346015" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
Condition 14 "3460346015" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
Condition 14 "3460346015" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (1 "011")
Condition 13 "1662645362" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
Condition 11 "2261547567" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (3 "10")
Condition 11 "2261547567" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
Condition 10 "378328037" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
Condition 10 "378328037" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
Condition 10 "378328037" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (1 "011")
ANNOTATION: " input_refclk_sel feature deprecated, only default 0 used "
Condition 37 "224274152" "(((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT == 2'b0) && (iREF_CLK == 1'b1)) || ((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1))) 1 -1" (2 "01")
ANNOTATION: " input_refclk_sel feature deprecated, only default 0 used "
Condition 39 "2895522335" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1)) 1 -1" (2 "10")
ANNOTATION: " input_refclk_sel feature deprecated, only default 0 used "
Condition 39 "2895522335" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1)) 1 -1" (3 "11")
CHECKSUM: "4049813162 2347369829"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_core.ublpwm_gen
ANNOTATION: " DBG_BL_PWM_INPUT_REFCLK_SELECT register is obsolete feature, confirmed as well by software team "
Condition 78 "1826709312" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1)) 1 -1" (1 "01")
ANNOTATION: " DBG_BL_PWM_INPUT_REFCLK_SELECT register is obsolete feature, confirmed as well by software team "
Condition 51 "1088840078" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1)) 1 -1" (1 "01")
ANNOTATION: " DBG_BL_PWM_INPUT_REFCLK_SELECT register is obsolete feature, confirmed as well by software team "
Condition 45 "3458347982" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1)) 1 -1" (1 "01")
ANNOTATION: " DBG_BL_PWM_INPUT_REFCLK_SELECT register is obsolete feature, confirmed as well by software team  "
Condition 38 "2895522335" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT != 2'b0) && (dbg_sclk_refclk_pulse == 1'b1)) 1 -1" (1 "01")
ANNOTATION: " DBG_BL_PWM_INPUT_REFCLK_SELECT register is obsolete feature, confirmed as well by software team  "
Condition 37 "3026573180" "((irf_DBG_BL_PWM_INPUT_REFCLK_SELECT == 2'b0) && (iREF_CLK == 1'b1)) 1 -1" (1 "01")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 59 "2138000859" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (2 "01")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 59 "2138000859" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 58 "3920987006" "((irf_BL_PWM_GRP1_REG_LOCK == 1'b0) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1))) 1 -1" (2 "10")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 46 "2937502913" "((do_db_reg_update == 1'b1) && (bl_pwm_ref_cnt == reg_BL_PWM_REF_DIV) && (dbg_bl_pwm_just_enabled_waiting_for_first_refclk != 1'b1)) 1 -1" (3 "110")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 25 "1617060809" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 17 "1904493209" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (2 "01")
ANNOTATION: "   Legacy code, compared againest Mero  "
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (4 "111")
ANNOTATION: " Legacy code, compared againest Mero "
Condition 13 "1662645362" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (2 "01")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 24 "2067887941" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 24 "2067887941" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 17 "1904493209" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (3 "10")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 17 "1904493209" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (1 "011")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 14 "3460346015" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 14 "3460346015" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 14 "3460346015" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (1 "011")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 12 "2860523178" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 12 "2860523178" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 12 "2860523178" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (1 "011")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 8 "3761564516" "((disp_capture_start_sclk_flopped == 1'b1) && (db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (4 "1110")
ANNOTATION: "  Legacy code, compared againest Mero "
Condition 8 "3761564516" "((disp_capture_start_sclk_flopped == 1'b1) && (db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "1101")
Condition 23 "939127057" "((irf_BL_PWM_GRP1_UPDATE_AT_FRAME_START == 1'b1) && (frame_start_already_received == 1'b0)) 1 -1" (2 "10")
Condition 21 "626146691" "((irf_BL_PWM_EN == 1'b1) && (BL_PWM_EN_rising_edge == 1'b1) && irf_BL_PWM_EN_EQ_ZERO) 1 -1" (1 "011")
Condition 16 "460157829" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1"
Condition 15 "2955745314" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
Condition 13 "1662645362" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
Condition 11 "2261547567" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (3 "10")
Condition 11 "2261547567" "((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) 1 -1" (1 "00")
Condition 10 "378328037" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (3 "110")
Condition 10 "378328037" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (2 "101")
Condition 10 "378328037" "((db_reg_values_pending_updates_imminent_to_occur == 1'b1) && ((iABM_BLPWM_bl_master_lock == 1'b0) || (irf_BL_PWM_GRP1_IGNORE_MASTER_LOCK_EN == 1'b1)) && (irf_BL_PWM_GRP1_REG_LOCK == 1'b0)) 1 -1" (1 "011")
CHECKSUM: "4049813162 2751466426"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_core.ublpwm_gen
ANNOTATION: "Legacy code, compared againest Mero"
Block 156 "1104666086" "do_db_reg_update = 1'b0;"
ANNOTATION: "Legacy code, compared againest Mero"
Block 163 "4211881408" "next_db_reg_update_state = 2'b1;"
ANNOTATION: "Legacy code, compared againest Mero"
Block 287 "1655083149" "next_bl_state = s_BLPWM_DISABLED;"
ANNOTATION: "compared vs Mero, it was covered by rbbmif_client_dcio_test which is part of dmu_sim_regress"
Block 193 "519086769" "next_update_bl_active_duty_cycle_int = {15'b0, reg_BL_ACTIVE_INT_FRAC_CNT[15]};"
ANNOTATION: "Legacy code, compared againest Mero, in Mero it is covered by rbbmif_client_dcio_test which is part of dmu_sim_regress"
Block 212 "4156787447" "next_update_bl_active_duty_cycle_frac = {reg_BL_ACTIVE_INT_FRAC_CNT[14:0], 1'b0};"
ANNOTATION: "will not get hit as all cases are defined"
Block 274 "3996536863" "dbg_sclk_count <= 2'b0;"
CHECKSUM: "4049813162 3040079599"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_core.ublpwm_gen
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 next_active_duty_cycle_cnt_frac_carry "net next_active_duty_cycle_cnt_frac_carry"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 next_active_duty_cycle_cnt_frac [16:16]"net next_active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 active_duty_cycle_cnt_frac [5:15]"reg active_duty_cycle_cnt_frac[16:0]"
Toggle active_duty_cycle_cnt_frac [16:16]"reg active_duty_cycle_cnt_frac[16:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle next_update_bl_active_duty_cycle_frac_flopped [0:0]"reg next_update_bl_active_duty_cycle_frac_flopped[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle next_update_bl_active_duty_cycle_frac [0:0]"reg next_update_bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " Legacy test does not cover all combination, UVM test does not test frac functionality "
Toggle 1to0 bl_active_duty_cycle_frac [5:15]"reg bl_active_duty_cycle_frac[15:0]"
ANNOTATION: " tied to 4'b1111 "
Toggle iREGS_be "net iREGS_be[3:0]"
ANNOTATION: " Default is 0 therefore toggling from 0->1 is enough "
Toggle 1to0 irf_BL_PWM_GRP1_READBACK_DB_REG_VALUE_EN "net irf_BL_PWM_GRP1_READBACK_DB_REG_VALUE_EN"
CHECKSUM: "4049813162 3846472135"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_core.ublpwm_gen
Fsm bl_state "3015518728"
ANNOTATION: " needs a reset in the middle of sequence, can be tested if DV tests get improved but not required "
Transition s_BLPWM_WAIT_FOR_1ST_REFCLK->s_BLPWM_DISABLED "2->0"
Fsm bl_state "3015518728"
ANNOTATION: " needs a reset in the middle of sequence, can be tested if DV tests get improved but not required "
Transition s_BLPWM_JUST_ENABLED->s_BLPWM_DISABLED "1->0"
Fsm db_reg_update_state "4098030394"
ANNOTATION: " BL_PWM_GRP1_UPDATE_AT_FRAME_START should not change while pending is asserted. "
Transition s_db_POST_FS_UPDATE_AT_END_BL_PERIOD->'h0 "3->0"
Fsm db_reg_update_state "4098030394"
ANNOTATION: " needs a reset in the middle of sequence, can be tested if DV tests get improved but not required "
Transition s_db_POST_FRAME_START_DELAY->'h0 "2->0"
