//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Tue Feb 22 16:51:37 2022
// ExclMode: default
//==================================================
CHECKSUM: "588157151 291485537"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_dlpc_cbus
ANNOTATION: " This means that accessing reserved register space for DCIO which is not needed. "
Condition 1 "3696445118" "((iDISP_ADDR[17:2] >= DLPC_DECODE_SPACE_LOWER) && (iDISP_ADDR[17:2] < DLPC_DECODE_SPACE_UPPER)) 1 -1" (2 "10")
CHECKSUM: "588157151 1754291360"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_dlpc_cbus
Toggle 1to0 DC_DLPC_cfg_mstrack "net DC_DLPC_cfg_mstrack"
Toggle 0to1 DC_DLPC_cfg_mstrack "net DC_DLPC_cfg_mstrack"
Toggle 1to0 iDISP_ADDR [17] "net iDISP_ADDR[17:2]"
Toggle 0to1 iDISP_ADDR [17] "net iDISP_ADDR[17:2]"
ANNOTATION: " fixed parameter "
Toggle RESERVED_DECODE_SPACE_LOWER "net RESERVED_DECODE_SPACE_LOWER[17:2]"
ANNOTATION: " it is a fixed value "
Toggle DLPC_DECODE_SPACE_UPPER "net DLPC_DECODE_SPACE_UPPER[17:2]"
ANNOTATION: " it is a fixed value "
Toggle DLPC_DECODE_SPACE_SIZE "net DLPC_DECODE_SPACE_SIZE[17:2]"
ANNOTATION: " fixed parameter "
Toggle DLPC_DECODE_SPACE_LOWER "net DLPC_DECODE_SPACE_LOWER[17:2]"
Toggle 1to0 DLPC_DC_cfg_mstrreq "net DLPC_DC_cfg_mstrreq"
Toggle 0to1 DLPC_DC_cfg_mstrreq "net DLPC_DC_cfg_mstrreq"
