//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Mon Mar 22 16:36:17 2021
// ExclMode: default
//==================================================
CHECKSUM: "2224341301 4279574096"
MODULE: dc_ati_master_clock_gater
ANNOTATION: " use en to control, pm_en tie low "
Toggle pm_enb "net pm_enb"
CHECKSUM: "2657106963 1123067632"
MODULE: ati_master_clock_gater
ANNOTATION: " use en to control, pm_en tie low "
Toggle pm_enb "net pm_enb"
ANNOTATION: " unused wire "
Toggle clock_enable_te "net clock_enable_te"

