//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Wed Oct 14 14:57:10 2020
// ExclMode: default
//==================================================
CHECKSUM: "1045415011 1062556597"
MODULE: dcn_apb_tx_fsm
ANNOTATION_BEGIN: "Only happens if wrtig or rtrig happens at the same time as pready in access state which is not possible as wtrig or rtrig asserts only when phyreg_ack got generated to unload a new entry from cmd_fifo. phyreg_ack gets generated in IDLE states as phyreg_ack is generated when \"pready & state == ACCESS\"."
Block 10 "1370251744" "next_state = SETUP;"
Block 31 "861637109" "psel <= 1'b1;"
Block 32 "4162852016" "pwdata <= apb_pwdata;"
ANNOTATION_END
CHECKSUM: "1045415011 1108595126"
MODULE: dcn_apb_tx_fsm
Fsm state "1108595126"
ANNOTATION: " Only happens if wrtig or rtrig happens at the same time as pready in access state which is not possible as wtrig or rtrig asserts only when phyreg_ack got generated to unload a new entry from cmd_fifo. phyreg_ack gets generated in IDLE states as phyreg_ack is generated when \"pready & state == ACCESS\". "
Transition ACCESS->SETUP "2->0"
ANNOTATION: " will not get covered unless there is a reset at this state "
Transition SETUP->IDLE "0->1"
CHECKSUM: "1045415011 1471704988"
MODULE: dcn_apb_tx_fsm
ANNOTATION_BEGIN: " Only happens if wrtig or rtrig happens at the same time as pready in access state which is not possible as wtrig or rtrig asserts only when phyreg_ack got generated to unload a new entry from cmd_fifo. phyreg_ack gets generated in IDLE states as phyreg_ack is generated when \"pready & state == ACCESS\". "
Condition 1 "3841784474" "(pready && transfer) 1 -1" (1 "01")
Condition 1 "3841784474" "(pready && transfer) 1 -1" (3 "11")
Condition 2 "1971550858" "(pready && ((~transfer))) 1 -1" (2 "10")
Condition 4 "2772151382" "(pready && transfer) 1 -1" (1 "01")
Condition 4 "2772151382" "(pready && transfer) 1 -1" (3 "11")
Condition 5 "2542299068" "(pready && ((~transfer))) 1 -1" (2 "10")
ANNOTATION_END
