//==================================================
// This file contains the Excluded objects
// Generated By User: winnimui
// Format Version: 2
// Date: Tue Feb 28 23:59:33 2023
// ExclMode: default
//==================================================
CHECKSUM: "656402849 1786951766"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dft_scan_marker_inst
ANNOTATION: " Connect in special cases only, if directed by DFT team "
Toggle Tile_ScanEn "net Tile_ScanEn[0:0]"
ANNOTATION: " Connect in special cases only, if directed by DFT team "
Toggle Tile_GaterEn "net Tile_GaterEn[0:0]"
ANNOTATION: " Connect in special cases only, if directed by DFT team "
Toggle Tile_DC_ScanEn "net Tile_DC_ScanEn[0:0]"
ANNOTATION: " Connect in special cases only, if directed by DFT team "
Toggle Stuck_At_Mode "net Stuck_At_Mode[0:0]"
ANNOTATION: " Connect in special cases only, if directed by DFT team "
Toggle Scm_Mode "net Scm_Mode[0:0]"
ANNOTATION: " Connect in special cases only, if directed by DFT team "
Toggle DC_TEST_CLK_EN "net DC_TEST_CLK_EN[0:0]"
ANNOTATION: " Connect in special cases only, if directed by DFT team "
Toggle Tile_Shift_Clk "net Tile_Shift_Clk[0:0]"
ANNOTATION: " Connect in special cases only, if directed by DFT team "
Toggle Scan_Pipeline_Clk "net Scan_Pipeline_Clk[0:0]"
Toggle 0to1 Async_Rstb_Scan_Override [0] "net Async_Rstb_Scan_Override[0:0]"
Toggle 1to0 Async_Rstb_Scan_Override [0] "net Async_Rstb_Scan_Override[0:0]"
Toggle 0to1 Scm_Async_Reset_Pulse [0] "net Scm_Async_Reset_Pulse[0:0]"
Toggle 1to0 Scm_Async_Reset_Pulse [0] "net Scm_Async_Reset_Pulse[0:0]"
Toggle 0to1 Async_Rstb_Scan_Override_Sel [0] "net Async_Rstb_Scan_Override_Sel[0:0]"
Toggle 1to0 Async_Rstb_Scan_Override_Sel [0] "net Async_Rstb_Scan_Override_Sel[0:0]"
