//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Wed Dec 22 15:38:22 2021
// ExclMode: default
//==================================================
CHECKSUM: "1535678871 947975084"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc.udlpc.udlpc_cmd_fifo
ANNOTATION_BEGIN: " There are only 7 (2^3) registers in dlpc  "
Toggle SLAVE_DEC_addr [15:3] "net SLAVE_DEC_addr[15:0]"
Toggle dlpc_reg_addr [15:3] "net dlpc_reg_addr[15:0]"
Toggle fifo_din [15:3] "net fifo_din[49:0]"
Toggle fifo_q [15:3] "reg fifo_q[49:0]"
ANNOTATION_END
ANNOTATION: " cmd fifo never gets full as ixtalin and cfg_clk are of the same frequency but async "
Toggle fifo_full "net fifo_full"
CHECKSUM: "1535678871 924625862"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc.udlpc.udlpc_cmd_fifo
ANNOTATION_BEGIN: " cmd fifo never gets full as ixtalin and cfg_clk are of the same frequency but async "
Condition 2 "3251279661" "(SLAVE_DEC_rdstr && ((!fifo_full))) 1 -1" (2 "10")
Condition 3 "4258758270" "(SLAVE_DEC_wrstr && ((!fifo_full))) 1 -1" (2 "10")
ANNOTATION_END
CHECKSUM: "3905158541 643732775"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc.udlpc.udlpc_cmd_fifo.udlpc_cmd_fifo
ANNOTATION_BEGIN: "internal to vid_asyncfifo_w_full module which is dclib module, assumed it was verified already"
Block 8 "1807408697" "if (push)"
Block 9 "4123627836" "q_full <= 1'b1;"
Block 10 "1652799847" ";"
ANNOTATION_END
CHECKSUM: "3905158541 1900997809"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc.udlpc.udlpc_cmd_fifo.udlpc_cmd_fifo
ANNOTATION_BEGIN: " There are only 7 (2^3) registers in dlpc  "
Toggle din [15:3] "net din[49:0]"
Toggle q_dout [15:3] "reg q_dout[49:0]"
ANNOTATION_END
ANNOTATION_BEGIN: " tied to 0 "
Toggle Rstwr_Clkr_InputChkDis "net Rstwr_Clkr_InputChkDis"
Toggle Rstwr_Clkw_InputChkDis "net Rstwr_Clkw_InputChkDis"
ANNOTATION_END
ANNOTATION: " cmd fifo never gets full as ixtalin and cfg_clk are of the same frequency but async "
Toggle q_full "reg q_full"
ANNOTATION: " unused "
Toggle almost_full "net almost_full"
ANNOTATION_BEGIN: " internal to vid_asyncfifo_w_full module which is dclib module, assumed it was verified already "
Toggle dout [15:3] "net dout[49:0]"
Toggle write_about_equal "net write_about_equal"
ANNOTATION_END
