//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Mon Dec 20 11:56:58 2021
// ExclMode: default
//==================================================
CHECKSUM: "2958485119 1265873389"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc.udlpc.udlpc_refclk_antiglitch
ANNOTATION_BEGIN: " tied to 1'b1 "
Toggle irf_SYMCLK_GATE_DISABLE "net irf_SYMCLK_GATE_DISABLE"
Toggle SYMCLK_GATE_DISABLE_symclk "net SYMCLK_GATE_DISABLE_symclk"
ANNOTATION_END
