//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Mon Feb  7 11:19:58 2022
// ExclMode: default
//==================================================
CHECKSUM: "2898269522 2846533655"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_dlpc_cbus.dlpc_config_if
Toggle 0to1 irf_BPHYC_INDEX [15] "net irf_BPHYC_INDEX[15:0]"
Toggle 1to0 irf_BPHYC_INDEX [15] "net irf_BPHYC_INDEX[15:0]"
Toggle 0to1 DC_BPHYC_cfg_mstrack "net DC_BPHYC_cfg_mstrack"
Toggle 1to0 DC_BPHYC_cfg_mstrack "net DC_BPHYC_cfg_mstrack"
Toggle 0to1 BPHYC_DC_cfg_mstrreq "net BPHYC_DC_cfg_mstrreq"
Toggle 1to0 BPHYC_DC_cfg_mstrreq "net BPHYC_DC_cfg_mstrreq"
