//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Tue Mar  1 10:53:15 2022
// ExclMode: default
//==================================================
CHECKSUM: "2207766359 1740679237"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc.udlpc.udlpc_core.udlpc_ctrl
ANNOTATION: "  counter value is not supposed to change to init value while DLPC_EN = 1   "
Condition 2 "2433401849" "(((!iDLPC_EN)) && iWTRIG_DLPC_COUNTER_INIT_VALUE) 1 -1" (1 "01")
CHECKSUM: "2207766359 1069720133"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc.udlpc.udlpc_core.udlpc_ctrl
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [31] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [13] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [14] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [15] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [16] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [17] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [18] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [19] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [20] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [21] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [22] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [23] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [24] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [25] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [26] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [27] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [28] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [29] "reg oSNAPSHOT_VALUE[31:0]"
ANNOTATION: " Did not get covered due to test randomization "
Toggle 1to0 oSNAPSHOT_VALUE [30] "reg oSNAPSHOT_VALUE[31:0]"
