//==================================================
// This file contains the Excluded objects
// Generated By User: winnimui
// Format Version: 2
// Date: Mon Apr  3 14:43:50 2023
// ExclMode: default
//==================================================
CHECKSUM: "2349710056 723872386"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc.DLPC_DC_cfg
ANNOTATION: " no backpressure for dlpc "
Toggle mstrreq "logic mstrreq"
CHECKSUM: "1861223936 1330037603"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc.DC_DLPC_cfg
ANNOTATION: " no backpressure for dlpc "
Toggle mstrack "logic mstrack"
CHECKSUM: "904085502 3642935573"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dlpc
ANNOTATION: " no backpressure for dlpc "
Toggle DLPC_DC_cfg_mstrreq "logic DLPC_DC_cfg_mstrreq"
ANNOTATION: " no backpressure for dlpc "
Toggle DC_DLPC_cfg_mstrack "logic DC_DLPC_cfg_mstrack"
Toggle 0to1 ZSC_VDDP_RESETn "logic ZSC_VDDP_RESETn"
Toggle 1to0 ZSC_VDDP_RESETn "logic ZSC_VDDP_RESETn"
