//==================================================
// This file contains the Excluded objects
// Generated By User: zeweigao
// Format Version: 2
// Date: Mon Jun 23 22:56:18 2025
// ExclMode: default
//==================================================
CHECKSUM: "2116028830 902237269"
MODULE: mai3c_1p8_tsmc3ne17m
ANNOTATION: "output port. it's for DFT"
Toggle Sami0 "net Sami0"
ANNOTATION: "connected to dbg port. don't use it now."
Toggle Art12 "net Art12"
ANNOTATION: "output port. it's for DFT"
Toggle Sami1 "net Sami1"
ANNOTATION: "not connected to any signal in housing wrp"
Toggle VSS_CORE "net VSS_CORE"
ANNOTATION: "not connected to our design. connected to external port"
Toggle PESD_I3C "net PESD_I3C"
ANNOTATION: "Powergood signals for glitch free opration. connected to external port"
Toggle cPwrgd "net cPwrgd"
ANNOTATION: "connected to dft_gasket. DFT RX enable"
Toggle TstRxEn1 "net TstRxEn1"
ANNOTATION: "connected to dft_gasket. DFT RX enable"
Toggle TstRxEn0 "net TstRxEn0"
ANNOTATION: "connected to dft_gasket. DFT RX enable"
Toggle TstTermEn1 "net TstTermEn1"
ANNOTATION: "connected to dft_gasket. DFT RX enable"
Toggle TstTermEn0 "net TstTermEn0"
ANNOTATION: "Powergood signals for glitch free opration. connected to external port"
Toggle sPwrgd "net sPwrgd"
ANNOTATION: "soft signals. connected to external port"
Toggle Soft0 "net Soft0"
ANNOTATION: "Pwrgood signals for Debug. connected to external port"
Toggle sPwrgd_Debug "net sPwrgd_Debug"
ANNOTATION: "Pwrgood signals for Debug. connected to external port"
Toggle RawPwrgd_Debug "net RawPwrgd_Debug"
ANNOTATION: "Power pin"
Toggle RawPwrgd "net RawPwrgd"
