//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Wed Mar  4 16:46:17 2020
// ExclMode: default
//==================================================
CHECKSUM: "3247798777 867148250"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_cmd_fifo
ANNOTATION_BEGIN: "   there are not that many registers in pwrseq, only 17 => 2^5 "
Toggle SLAVE_DEC_addr [15:5] "net SLAVE_DEC_addr[15:0]"
Toggle pwrseq_reg_addr [15:5] "net pwrseq_reg_addr[15:0]"
Toggle fifo_din [15:5] "net fifo_din[49:0]"
Toggle fifo_q [15:5] "reg fifo_q[49:0]"
ANNOTATION_END
ANNOTATION: " cmd fifo never gets full as ixtalin and cfg_clk are of the same frequency but async "
Toggle fifo_full "net fifo_full"
CHECKSUM: "3247798777 924625862"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_cmd_fifo
ANNOTATION_BEGIN: " cmd fifo never gets full as ixtalin and cfg_clk are of the same frequency but async "
Condition 2 "3251279661" "(SLAVE_DEC_rdstr && ((!fifo_full))) 1 -1" (2 "10")
Condition 3 "4258758270" "(SLAVE_DEC_wrstr && ((!fifo_full))) 1 -1" (2 "10")
ANNOTATION_END
CHECKSUM: "3247798777 867148250"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_cmd_fifo
ANNOTATION_BEGIN: "   there are not that many registers in pwrseq, only 17 => 2^5 "
Toggle SLAVE_DEC_addr [15:5] "net SLAVE_DEC_addr[15:0]"
Toggle pwrseq_reg_addr [15:5] "net pwrseq_reg_addr[15:0]"
Toggle fifo_din [15:5] "net fifo_din[49:0]"
Toggle fifo_q [15:5] "reg fifo_q[49:0]"
ANNOTATION_END
ANNOTATION: " cmd fifo never gets full as ixtalin and cfg_clk are of the same frequency but async "
Toggle fifo_full "net fifo_full"
CHECKSUM: "3247798777 924625862"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_cmd_fifo
ANNOTATION_BEGIN: " cmd fifo never gets full as ixtalin and cfg_clk are of the same frequency but async "
Condition 2 "3251279661" "(SLAVE_DEC_rdstr && ((!fifo_full))) 1 -1" (2 "10")
Condition 3 "4258758270" "(SLAVE_DEC_wrstr && ((!fifo_full))) 1 -1" (2 "10")
ANNOTATION_END
