//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Fri Apr 16 12:33:10 2021
// ExclMode: default
//==================================================
CHECKSUM: "2224341301 4279574096"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.uCFGCLK_GATER
ANNOTATION: " tied to 0 "
Toggle pm_enb "net pm_enb"
CHECKSUM: "2657106963 1123067632"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.uCFGCLK_GATER.uati_master_clock_gater
ANNOTATION: " tied to 0 "
Toggle pm_enb "net pm_enb"
ANNOTATION: " unused "
Toggle clock_enable_te "net clock_enable_te"
CHECKSUM: "2118881909 1265873389"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_refclk_antiglitch
ANNOTATION_BEGIN: "  tied to 1'b1 "
Toggle irf_SYMCLK_ENABLE "net irf_SYMCLK_ENABLE"
Toggle irf_SYMCLK_GATE_DISABLE "net irf_SYMCLK_GATE_DISABLE"
Toggle rf_symclk_enable "net rf_symclk_enable"
Toggle SYMCLK_ENABLE_REFCLK "net SYMCLK_ENABLE_REFCLK"
Toggle SYMCLK_GATE_DISABLE_symclk "net SYMCLK_GATE_DISABLE_symclk"
ANNOTATION_END
CHECKSUM: "2118881909 4241272726"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_refclk_antiglitch
ANNOTATION: " rf_symclk_enable is tied to 1'b1 "
Condition 2 "2273493789" "((symclk_reset == 1'b1) || (rf_symclk_enable == 1'b0)) 1 -1" (2 "01")
