//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Tue Mar 24 13:53:16 2020
// ExclMode: default
//==================================================
CHECKSUM: "3481813986 3338288901"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_refgen
ANNOTATION: " tied to 0 "
Toggle oPWRSEQ_REFGEN_debug_data [29:0] "net oPWRSEQ_REFGEN_debug_data[31:0]"
CHECKSUM: "3481813986 2607837807"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_refgen
ANNOTATION: " it is randomized in test so may take a while to get hit "
Condition 1 "3312820211" "((microsecond_cnt != 7'b0) || (microsecond_ref != 1'b0)) 1 -1" (2 "01")
ANNOTATION: " software does not toggle bl_pwm_en, also it is randomized in test so may take a while to get hit "
Condition 2 "3598142484" "((xtal_ref_cnt != 7'b0) || (xtal_ref != 1'b0)) 1 -1" (2 "01")
CHECKSUM: "3481813986 3338288901"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_refgen
ANNOTATION: " tied to 0 "
Toggle oPWRSEQ_REFGEN_debug_data [29:0] "net oPWRSEQ_REFGEN_debug_data[31:0]"
CHECKSUM: "3481813986 2607837807"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_refgen
ANNOTATION: " it is randomized in test so may take a while to get hit "
Condition 1 "3312820211" "((microsecond_cnt != 7'b0) || (microsecond_ref != 1'b0)) 1 -1" (2 "01")
ANNOTATION: " software does not toggle bl_pwm_en, also it is randomized in test so may take a while to get hit "
Condition 2 "3598142484" "((xtal_ref_cnt != 7'b0) || (xtal_ref != 1'b0)) 1 -1" (2 "01")
