//==================================================
// This file contains the Excluded objects
// Generated By User: youkim
// Format Version: 2
// Date: Tue Mar 25 16:25:01 2025
// ExclMode: default
//==================================================
CHECKSUM: "2613369188 4035100102"
MODULE: pwrseq_glue_logic
ANNOTATION_BEGIN: " tied to 0 "
Toggle PWRSEQ_CORE_debug_data [24:0] "net PWRSEQ_CORE_debug_data[31:0]"
Toggle PWRSEQ_REFGEN_debug_data [29:0] "net PWRSEQ_REFGEN_debug_data[31:0]"
Toggle CBUS_SLAVE_debug_data [2] "net CBUS_SLAVE_debug_data[31:0]"
Toggle CBUS_SLAVE_debug_data [6] "net CBUS_SLAVE_debug_data[31:0]"
Toggle CBUS_SLAVE_debug_data [31:21] "net CBUS_SLAVE_debug_data[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [0] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [2] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [5] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [8:7] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [10] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [13] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [16:15] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [18] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [21] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA0_xtalin [31:23] "reg PWRSEQ_DEBUG_DATA0_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA1_xtalin [24:0] "reg PWRSEQ_DEBUG_DATA1_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA2_xtalin [29:0] "reg PWRSEQ_DEBUG_DATA2_xtalin[31:0]"
Toggle PWRSEQ_DEBUG_DATA_cfgclk [2] "reg PWRSEQ_DEBUG_DATA_cfgclk[31:0]"
Toggle PWRSEQ_DEBUG_DATA_cfgclk [6] "reg PWRSEQ_DEBUG_DATA_cfgclk[31:0]"
Toggle PWRSEQ_DEBUG_DATA_cfgclk [31:21] "reg PWRSEQ_DEBUG_DATA_cfgclk[31:0]"
ANNOTATION_END
