//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Mon Apr 20 15:04:25 2020
// ExclMode: default
//==================================================
CHECKSUM: "1963723840 4067125380"
MODULE: pwrseq_core
ANNOTATION: "default is not reachable"
Block 45 "3076501821" "DIGON = 1'b0;"
CHECKSUM: "1963723840 1620118303"
MODULE: pwrseq_core
ANNOTATION_BEGIN: " obsolete feature "
Toggle irf_SYNCEN "net irf_SYNCEN"
Toggle irf_SYNCEN_OVRD "net irf_SYNCEN_OVRD"
Toggle irf_SYNCEN_POL "net irf_SYNCEN_POL"
ANNOTATION_END
ANNOTATION_BEGIN: " default value is 0, so 0->1 testing is good "
Toggle 1to0 irf_DIGON_OVRD "net irf_DIGON_OVRD"
Toggle 1to0 irf_DIGON_POL "net irf_DIGON_POL"
Toggle 1to0 irf_BLON_OVRD "net irf_BLON_OVRD"
ANNOTATION_END
ANNOTATION: " default value is 0 "
Toggle 1to0 irf_BL_PWM_GRP1_READBACK_DB_REG_VALUE_EN "net irf_BL_PWM_GRP1_READBACK_DB_REG_VALUE_EN"
ANNOTATION: " tied to 4'b1111 "
Toggle iDCIOREGS_be "net iDCIOREGS_be[3:0]"
ANNOTATION: " tied to 0 "
Toggle oPWRSEQ_CORE_debug_data [24:0] "net oPWRSEQ_CORE_debug_data[31:0]"
CHECKSUM: "1963723840 2619328371"
MODULE: pwrseq_core
Fsm PWRSEQ_STATE "2619328371"
ANNOTATION_BEGIN: " not a possibility from FSM unless a reset happens in the middle of sequence, can be tested if DV tests get improved but not required "
Transition POWERDOWN0->DISABLED "5->0"
Transition POWERDOWN1->DISABLED "6->0"
Transition POWERDOWN2->DISABLED "7->0"
Transition POWERDOWN3->DISABLED "11->0"
Transition POWERDOWN_DELAY->DISABLED "8->0"
Transition POWERUP2->DISABLED "3->0"
Transition POWERUP3->DISABLED "10->0"
ANNOTATION_END
ANNOTATION_BEGIN: "  not a possibility from FSM unless a reset happens in the middle of sequence, can be tested if DV tests get improved but not required  "
Transition POWERUP0->DISABLED "1->0"
Transition POWERUP1->DISABLED "2->0"
ANNOTATION_END
