//==================================================
// This file contains the Excluded objects
// Generated By User: winnimui
// Format Version: 2
// Date: Wed May 26 17:54:51 2021
// ExclMode: default
//==================================================
CHECKSUM: "3513283339 2310636480"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_pad_control
ANNOTATION: "DCIO_PWRSEQ_OVERLOAD_DIGON is tiged of to 0 in DCIO so condition is never true"
Block 9 "2589186220" "oDIGON_EN = 1'b1;"
CHECKSUM: "3513283339 2448911884"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_pad_control
ANNOTATION_BEGIN: " tied to 0 in DCIO "
Toggle DCIO_PWRSEQ_OVERLOAD_DIGON "net DCIO_PWRSEQ_OVERLOAD_DIGON"
Toggle DCIO_PWRSEQ_OVERLOAD_VALUE_DIGON "net DCIO_PWRSEQ_OVERLOAD_VALUE_DIGON"
ANNOTATION_END
