//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Sat Feb 22 23:16:03 2020
// ExclMode: default
//==================================================
CHECKSUM: "3523960269 2846533655"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq1_config_if
ANNOTATION: "  out of dcn address range (according to register map we have 19458 registers which is 2^15)  "
Toggle irf_BPHYC_INDEX [15] "net irf_BPHYC_INDEX[15:0]"
ANNOTATION: " no backpressure from pwrseq, therefore, no ack from master(dcio)  "
Toggle DC_BPHYC_cfg_mstrack "net DC_BPHYC_cfg_mstrack"
ANNOTATION: "  no backpressure from pwrseq  "
Toggle BPHYC_DC_cfg_mstrreq "net BPHYC_DC_cfg_mstrreq"
CHECKSUM: "3523960269 2846533655"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq0_config_if
ANNOTATION: " out of dcn address range (according to register map we have 19458 registers which is 2^15) "
Toggle irf_BPHYC_INDEX [15] "net irf_BPHYC_INDEX[15:0]"
ANNOTATION: " no backpressure from pwrseq, therefore, no ack from master(dcio) "
Toggle DC_BPHYC_cfg_mstrack "net DC_BPHYC_cfg_mstrack"
ANNOTATION: " no backpressure from pwrseq "
Toggle BPHYC_DC_cfg_mstrreq "net BPHYC_DC_cfg_mstrreq"
CHECKSUM: "1412733900 2895668581"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq1_config_if.udc_phycfg_mstrif
ANNOTATION_BEGIN: "no backpressure from pwrseq"
Block 9 "1608569662" "if (PhyReqMaster)"
Block 10 "2379079779" "eHUBPHYstate = 4'b1;"
Block 18 "1037588619" "eHUBPHYstate = (PhyReqMaster ? 4'b1 : 4'b0011);"
Block 19 "1013988079" "eHUBPHYstate = (ArbRelease ? 4'b0 : 4'b0011);"
Block 30 "2718501902" "if ((HUBPHYstate == 4'b1))"
Block 31 "3930406507" "WaitCount <= 3'b111;"
Block 36 "3151634993" "Last_cmd <= 1'b0;"
ANNOTATION_END
CHECKSUM: "1412733900 83971080"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq1_config_if.udc_phycfg_mstrif
ANNOTATION: " no backpressure from pwrseq, therefore, no ack from master(dcio)  "
Toggle oPhyCfg_CfgAckMaster "reg oPhyCfg_CfgAckMaster"
ANNOTATION_BEGIN: "  no backpressure from pwrseq  "
Toggle iPhyCfg_PhyReqMaster "net iPhyCfg_PhyReqMaster"
Toggle PhyReqMaster "net PhyReqMaster"
ANNOTATION_END
ANNOTATION_BEGIN: "   there are not that many registers in pwrseq, only 17 => 2^5 "
Toggle Phy_RegAddr_sync [15:5] "net Phy_RegAddr_sync[15:0]"
Toggle Phy_RegAddr_sync_reg [15:5] "reg Phy_RegAddr_sync_reg[15:0]"
Toggle AdrPhase0 "net AdrPhase0[7:0]"
Toggle AdrPhase1 [7:5] "net AdrPhase1[7:0]"
ANNOTATION_END
CHECKSUM: "1412733900 982748297"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq1_config_if.udc_phycfg_mstrif
Fsm HUBPHYstate "787729510"
ANNOTATION_BEGIN: "  no backpressure from pwrseq  "
State CFGHUB_PHYEXT "1"
State CFGHUB_PHYRELEASE "3"
ANNOTATION_END
ANNOTATION_BEGIN: " Not possible according to spec "
Transition CFGHUB_PHYADR1->CFGHUB_PHYIDLE "10->0"
Transition CFGHUB_PHYEXT->CFGHUB_PHYIDLE "1->0"
Transition CFGHUB_PHYRWAIT->CFGHUB_PHYIDLE "4->0"
Transition CFGHUB_PHYWDATA0->CFGHUB_PHYIDLE "14->0"
Transition CFGHUB_PHYWDATA1->CFGHUB_PHYIDLE "15->0"
Transition CFGHUB_PHYWDATA2->CFGHUB_PHYIDLE "11->0"
Transition CFGHUB_PHYWDATA3->CFGHUB_PHYIDLE "9->0"
ANNOTATION_END
ANNOTATION_BEGIN: "  no backpressure from pwrseq  "
Transition CFGHUB_PHYEXT->CFGHUB_PHYRELEASE "1->3"
Transition CFGHUB_PHYIDLE->CFGHUB_PHYEXT "0->1"
Transition CFGHUB_PHYRELEASE->CFGHUB_PHYIDLE "3->0"
ANNOTATION_END
CHECKSUM: "1412733900 2175246917"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq1_config_if.udc_phycfg_mstrif
ANNOTATION_BEGIN: "  no backpressure from pwrseq  "
Condition 7 "1082309678" "(PhyReqMaster ? 4'b1 : 4'b0011) 1 -1"
Condition 8 "401540368" "(ArbRelease ? 4'b0 : 4'b0011) 1 -1"
Condition 11 "205275741" "((HUBPHYstate == 4'b0) && PhyReqMaster) 1 -1"
ANNOTATION_END
CHECKSUM: "1412733900 2895668581"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq0_config_if.udc_phycfg_mstrif
ANNOTATION_BEGIN: "no backpressure from pwrseq"
Block 9 "1608569662" "if (PhyReqMaster)"
Block 10 "2379079779" "eHUBPHYstate = 4'b1;"
Block 18 "1037588619" "eHUBPHYstate = (PhyReqMaster ? 4'b1 : 4'b0011);"
Block 19 "1013988079" "eHUBPHYstate = (ArbRelease ? 4'b0 : 4'b0011);"
Block 30 "2718501902" "if ((HUBPHYstate == 4'b1))"
Block 31 "3930406507" "WaitCount <= 3'b111;"
Block 36 "3151634993" "Last_cmd <= 1'b0;"
ANNOTATION_END
CHECKSUM: "1412733900 83971080"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq0_config_if.udc_phycfg_mstrif
ANNOTATION: " no backpressure from pwrseq, therefore, no ack from master(dcio)  "
Toggle oPhyCfg_CfgAckMaster "reg oPhyCfg_CfgAckMaster"
ANNOTATION_BEGIN: "  no backpressure from pwrseq  "
Toggle iPhyCfg_PhyReqMaster "net iPhyCfg_PhyReqMaster"
Toggle PhyReqMaster "net PhyReqMaster"
ANNOTATION_END
ANNOTATION_BEGIN: "   there are not that many registers in pwrseq, only 17 => 2^5 "
Toggle Phy_RegAddr_sync [15:5] "net Phy_RegAddr_sync[15:0]"
Toggle Phy_RegAddr_sync_reg [15:5] "reg Phy_RegAddr_sync_reg[15:0]"
Toggle AdrPhase0 "net AdrPhase0[7:0]"
Toggle AdrPhase1 [7:5] "net AdrPhase1[7:0]"
ANNOTATION_END
CHECKSUM: "1412733900 982748297"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq0_config_if.udc_phycfg_mstrif
Fsm HUBPHYstate "787729510"
ANNOTATION_BEGIN: "  no backpressure from pwrseq  "
State CFGHUB_PHYEXT "1"
State CFGHUB_PHYRELEASE "3"
ANNOTATION_END
ANNOTATION_BEGIN: " Not possible according to spec "
Transition CFGHUB_PHYADR1->CFGHUB_PHYIDLE "10->0"
Transition CFGHUB_PHYEXT->CFGHUB_PHYIDLE "1->0"
Transition CFGHUB_PHYRWAIT->CFGHUB_PHYIDLE "4->0"
Transition CFGHUB_PHYWDATA0->CFGHUB_PHYIDLE "14->0"
Transition CFGHUB_PHYWDATA1->CFGHUB_PHYIDLE "15->0"
Transition CFGHUB_PHYWDATA2->CFGHUB_PHYIDLE "11->0"
Transition CFGHUB_PHYWDATA3->CFGHUB_PHYIDLE "9->0"
ANNOTATION_END
ANNOTATION_BEGIN: "  no backpressure from pwrseq  "
Transition CFGHUB_PHYEXT->CFGHUB_PHYRELEASE "1->3"
Transition CFGHUB_PHYIDLE->CFGHUB_PHYEXT "0->1"
Transition CFGHUB_PHYRELEASE->CFGHUB_PHYIDLE "3->0"
ANNOTATION_END
CHECKSUM: "1412733900 2175246917"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.udcio_pwrseq_cbus.pwrseq0_config_if.udc_phycfg_mstrif
ANNOTATION_BEGIN: "  no backpressure from pwrseq  "
Condition 7 "1082309678" "(PhyReqMaster ? 4'b1 : 4'b0011) 1 -1"
Condition 8 "401540368" "(ArbRelease ? 4'b0 : 4'b0011) 1 -1"
Condition 11 "205275741" "((HUBPHYstate == 4'b0) && PhyReqMaster) 1 -1" (1 "01")
Condition 11 "205275741" "((HUBPHYstate == 4'b0) && PhyReqMaster) 1 -1" (3 "11")
ANNOTATION_END
