//==================================================
// This file contains the Excluded objects
// Generated By User: winnimui
// Format Version: 2
// Date: Wed May 26 17:25:13 2021
// ExclMode: default
//==================================================
CHECKSUM: "4106180442"
ANNOTATION: "    tied to 1 in pwrseq0    "
INSTANCE:tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.RCU_DC_hard
CHECKSUM: "217081580 1931003351"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0
ANNOTATION: " tied to 1 in pwrseq0 "
Toggle RCU_DC_hard_resetb "logic RCU_DC_hard_resetb"
ANNOTATION_BEGIN: " tied off "
Toggle ZSC_VDDP_RESETn "logic ZSC_VDDP_RESETn"
Toggle DC_PWRSEQ_interceptb "logic DC_PWRSEQ_interceptb"
ANNOTATION_END
ANNOTATION: " no backpressure from pwrseq, therefore, no ack from master(dcio) "
Toggle DC_PWRSEQ_cfg_mstrack "logic DC_PWRSEQ_cfg_mstrack"
ANNOTATION: " no backpressure from pwrseq "
Toggle PWRSEQ_DC_cfg_mstrreq "logic PWRSEQ_DC_cfg_mstrreq"
ANNOTATION_BEGIN: " tied to 0 in dcio "
Toggle DCIO_PWRSEQ_OVERLOAD_DIGON "logic DCIO_PWRSEQ_OVERLOAD_DIGON"
Toggle DCIO_PWRSEQ_OVERLOAD_VALUE_DIGON "logic DCIO_PWRSEQ_OVERLOAD_VALUE_DIGON"
ANNOTATION_END
ANNOTATION_BEGIN: " tied to 0 "
Toggle PWRSEQ_DEBUG_OUT [2] "logic PWRSEQ_DEBUG_OUT[31:0]"
Toggle PWRSEQ_DEBUG_OUT [21] "logic PWRSEQ_DEBUG_OUT[31:0]"
Toggle PWRSEQ_DEBUG_OUT [24:23] "logic PWRSEQ_DEBUG_OUT[31:0]"
Toggle PWRSEQ_DEBUG_CLK_OUT "logic PWRSEQ_DEBUG_CLK_OUT"
ANNOTATION_END
CHECKSUM: "2079348867 1330037603"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.DC_PWRSEQ_cfg
ANNOTATION: " no backpressure from pwrseq, therefore, no ack from master(dcio) "
Toggle mstrack "logic mstrack"
CHECKSUM: "2226049846 723872386"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.PWRSEQ_DC_cfg
ANNOTATION: " no backpressure from pwrseq "
Toggle mstrreq "logic mstrreq"
