//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Mon Feb 24 10:36:22 2020
// ExclMode: default
//==================================================
CHECKSUM: "3925588947 1152321221"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_cbus_slave
ANNOTATION: " no backpressure from pwrseq, therefore, no ack from master(dcio)  "
Toggle DC_PWRSEQ_cfg_mstrAck "net DC_PWRSEQ_cfg_mstrAck"
ANNOTATION_BEGIN: " no req from pwrseq "
Toggle PWRSEQ_DC_cfg_slvReq "net PWRSEQ_DC_cfg_slvReq"
Toggle CBUS_SLAVE_debug_data [12:6] "net CBUS_SLAVE_debug_data[31:0]"
Toggle regArbFsm_next_state "net regArbFsm_next_state[1:0]"
ANNOTATION_END
ANNOTATION: "   there are not that many registers in pwrseq, only 17 => 2^5 "
Toggle SLAVE_DEC_addr [15:5] "net SLAVE_DEC_addr[15:0]"
ANNOTATION_BEGIN: " tied to 0 "
Toggle CBUS_SLAVE_debug_data [2] "net CBUS_SLAVE_debug_data[31:0]"
Toggle CBUS_SLAVE_debug_data [31:16] "net CBUS_SLAVE_debug_data[31:0]"
Toggle dft_req_pending "net dft_req_pending"
Toggle dft_reg_holdArb "net dft_reg_holdArb"
Toggle dft_bypassArb_cfgclk "net dft_bypassArb_cfgclk"
Toggle dft_req_cfgclk "net dft_req_cfgclk"
Toggle dft_rst_cfgclk "net dft_rst_cfgclk"
ANNOTATION_END
ANNOTATION: " not possible "
Toggle dft_cycle_cntr_en "net dft_cycle_cntr_en"
ANNOTATION: " not possible to toggle "
Toggle zeroRd_cntr_en "net zeroRd_cntr_en"
CHECKSUM: "3925588947 1152321221"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_cbus_slave
ANNOTATION: " no backpressure from pwrseq, therefore, no ack from master(dcio)  "
Toggle DC_PWRSEQ_cfg_mstrAck "net DC_PWRSEQ_cfg_mstrAck"
ANNOTATION_BEGIN: " no req from pwrseq "
Toggle PWRSEQ_DC_cfg_slvReq "net PWRSEQ_DC_cfg_slvReq"
Toggle CBUS_SLAVE_debug_data [12:6] "net CBUS_SLAVE_debug_data[31:0]"
Toggle regArbFsm_next_state "net regArbFsm_next_state[1:0]"
ANNOTATION_END
ANNOTATION: "   there are not that many registers in pwrseq, only 17 => 2^5 "
Toggle SLAVE_DEC_addr [15:5] "net SLAVE_DEC_addr[15:0]"
ANNOTATION_BEGIN: " tied to 0 "
Toggle CBUS_SLAVE_debug_data [2] "net CBUS_SLAVE_debug_data[31:0]"
Toggle CBUS_SLAVE_debug_data [31:16] "net CBUS_SLAVE_debug_data[31:0]"
Toggle dft_req_pending "net dft_req_pending"
Toggle dft_reg_holdArb "net dft_reg_holdArb"
Toggle dft_bypassArb_cfgclk "net dft_bypassArb_cfgclk"
Toggle dft_req_cfgclk "net dft_req_cfgclk"
Toggle dft_rst_cfgclk "net dft_rst_cfgclk"
ANNOTATION_END
ANNOTATION: " not possible "
Toggle dft_cycle_cntr_en "net dft_cycle_cntr_en"
ANNOTATION: " not possible to toggle "
Toggle zeroRd_cntr_en "net zeroRd_cntr_en"
