//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Wed Dec 22 16:07:48 2021
// ExclMode: default
//==================================================
CHECKSUM: "3905158541 643732775"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_cmd_fifo.upwrseq_cmd_fifo
ANNOTATION_BEGIN: "internal to vid_asyncfifo_w_full module which is dclib module, assumed it was verified already"
Block 8 "1807408697" "if (push)"
Block 9 "4123627836" "q_full <= 1'b1;"
Block 10 "1652799847" ";"
ANNOTATION_END
CHECKSUM: "3905158541 1900997809"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_cmd_fifo.upwrseq_cmd_fifo
ANNOTATION_BEGIN: " There are 16 (2^4) registers in pwrseq "
Toggle din [15:4] "net din[49:0]"
Toggle q_dout [15:4] "reg q_dout[49:0]"
ANNOTATION_END
ANNOTATION_BEGIN: " tied to 0 "
Toggle Rstwr_Clkr_InputChkDis "net Rstwr_Clkr_InputChkDis"
Toggle Rstwr_Clkw_InputChkDis "net Rstwr_Clkw_InputChkDis"
ANNOTATION_END
ANNOTATION: " cmd fifo never gets full as ixtalin and cfg_clk are of the same frequency but async "
Toggle q_full "reg q_full"
ANNOTATION: " unused "
Toggle almost_full "net almost_full"
ANNOTATION_BEGIN: " internal to vid_asyncfifo_w_full module which is dclib module, assumed it was verified already "
Toggle dout [15:5] "net dout[49:0]"
Toggle write_about_equal "net write_about_equal"
ANNOTATION_END
CHECKSUM: "3905158541 1702384952"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq0.upwrseq0.upwrseq_cmd_fifo.upwrseq_cmd_fifo
ANNOTATION: " internal to vid_asyncfifo_w_full module which is dclib module, assumed it was verified already "
Condition 6 "2599699108" "((q_sync_write_ctr == read_ctr_sel) || (resetread == 1'b1)) 1 -1" (2 "01")
CHECKSUM: "3905158541 643732775"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_cmd_fifo.upwrseq_cmd_fifo
ANNOTATION_BEGIN: "internal to vid_asyncfifo_w_full module which is dclib module, assumed it was verified already"
Block 8 "1807408697" "if (push)"
Block 9 "4123627836" "q_full <= 1'b1;"
Block 10 "1652799847" ";"
ANNOTATION_END
CHECKSUM: "3905158541 1900997809"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_cmd_fifo.upwrseq_cmd_fifo
ANNOTATION_BEGIN: " There are 16 (2^4) registers in pwrseq "
Toggle din [15:4] "net din[49:0]"
Toggle q_dout [15:4] "reg q_dout[49:0]"
ANNOTATION_END
ANNOTATION_BEGIN: " tied to 0 "
Toggle Rstwr_Clkr_InputChkDis "net Rstwr_Clkr_InputChkDis"
Toggle Rstwr_Clkw_InputChkDis "net Rstwr_Clkw_InputChkDis"
ANNOTATION_END
ANNOTATION: " cmd fifo never gets full as ixtalin and cfg_clk are of the same frequency but async "
Toggle q_full "reg q_full"
ANNOTATION: " unused "
Toggle almost_full "net almost_full"
ANNOTATION_BEGIN: " internal to vid_asyncfifo_w_full module which is dclib module, assumed it was verified already "
Toggle dout [15:5] "net dout[49:0]"
Toggle write_about_equal "net write_about_equal"
ANNOTATION_END
CHECKSUM: "3905158541 1702384952"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.pwrseq1.upwrseq0.upwrseq_cmd_fifo.upwrseq_cmd_fifo
ANNOTATION: " internal to vid_asyncfifo_w_full module which is dclib module, assumed it was verified already "
Condition 6 "2599699108" "((q_sync_write_ctr == read_ctr_sel) || (resetread == 1'b1)) 1 -1" (2 "01")
