//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Fri Dec 17 10:23:56 2021
// ExclMode: default
//==================================================
CHECKSUM: "2492029868 2619259864"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.uRBBMIF_DLY
ANNOTATION_BEGIN: "internal to dc_pipeline_vld which is a dcnlib module, assumed to be verified already"
Block 2 "3433969155" "genblk1.out_vld[(genblk1.i + 1)] <= genblk1.out_vld[genblk1.i];"
Block 10 "2446275293" "if (genblk1.out_vld[genblk1.i])"
Block 11 "1514329028" "genblk1.out_data[(genblk1.i + 1)] <= genblk1.out_data[genblk1.i];"
ANNOTATION_END
CHECKSUM: "2492029868 403383245"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.dcio.udcio.uRBBMIF_DLY
ANNOTATION_BEGIN: " out of dcn address range (according to register map we have 19458 registers which is 2^15) "
Toggle i_in_data [88] "net i_in_data[88:0]"
Toggle o_out_data [88] "net o_out_data[88:0]"
ANNOTATION_END
ANNOTATION_BEGIN: " Byte enable signal, all 4 bytes are enabled and never gets disabled "
Toggle 1to0 i_in_data [37:34] "net i_in_data[88:0]"
Toggle 1to0 o_out_data [37:34] "net o_out_data[88:0]"
ANNOTATION_END
