//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Wed Feb 10 10:54:23 2021
// ExclMode: default
//==================================================
CHECKSUM: "1433432378 3878082500"
INSTANCE:  tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cbus_slave
ANNOTATION: " There are only 54 registers in rdpcstx "
Toggle SLAVE_DEC_addr [15:6] "net SLAVE_DEC_addr[15:0]"
ANNOTATION: " set to addr 44 "
Toggle irf_pll_atomic_update_reg_addr "net irf_pll_atomic_update_reg_addr[15:0]"
ANNOTATION: " unused for pll atomic update "
Toggle irf_pll_atomic_update_reg_data [31:1] "net irf_pll_atomic_update_reg_data[31:0]"
ANNOTATION: " software needs to toggle bit0  from 0->1 (which it does) to write 1 and then write 1 to DPCS_TX_PLL_UPDATE_REQ to trigger atomic update "
Toggle 1to0 irf_pll_atomic_update_reg_data [0] "net irf_pll_atomic_update_reg_data[31:0]"
ANNOTATION_BEGIN: " tied to 0 "
Toggle CBUS_SLAVE_debug_data [2] "net CBUS_SLAVE_debug_data[23:0]"
Toggle CBUS_SLAVE_debug_data [18:16] "net CBUS_SLAVE_debug_data[23:0]"
Toggle CBUS_SLAVE_debug_data [23:20] "net CBUS_SLAVE_debug_data[23:0]"
ANNOTATION_END
ANNOTATION: " DFT_BPHYC_reg_bypassArb is tied to 0.  So zeroRd_cntr_en stays at 0. "
Toggle zeroRd_cntr_en "net zeroRd_cntr_en"
ANNOTATION: " DFT_BPHYC_reg_holdArb is tied to 0. "
Toggle dft_reg_holdArb "net dft_reg_holdArb"
ANNOTATION: " DFT_BPHYC_reg_bypassArb is tied to 0. "
Toggle dft_bypassArb_cfgclk "net dft_bypassArb_cfgclk"
ANNOTATION: " DFT_BPHYC_reg_rst is tied to 0. "
Toggle dft_rst_cfgclk "net dft_rst_cfgclk"
CHECKSUM: "1433432378 3878082500"
// INSTANCE:  tb.gpu0.chip0.core.udpcssys_tb_usb.dpcssys_tb_c20_usb0.rdpcs_pipe_usb.urdpcs_pipe_usb0.urdpcs_cbus_slave
MODULE: rdpcs_cbus_slave
ANNOTATION: " There are only 43 registers in rdpcs_pipe "
Toggle SLAVE_DEC_addr [15:6] "net SLAVE_DEC_addr[15:0]"
ANNOTATION: "  Address is set to phy address 0x111 to update on v_update event "
Toggle irf_pll_atomic_update_reg_addr "net irf_pll_atomic_update_reg_addr[15:0]"
ANNOTATION_BEGIN: " tied to 0 "
Toggle irf_pll_atomic_update_reg_data [31:16] "net irf_pll_atomic_update_reg_data[31:0]"
Toggle CBUS_SLAVE_debug_data [2] "net CBUS_SLAVE_debug_data[23:0]"
Toggle CBUS_SLAVE_debug_data [23:21] "net CBUS_SLAVE_debug_data[23:0]"
ANNOTATION_END
