//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Thu Oct 15 12:17:34 2020
// ExclMode: default
//==================================================
CHECKSUM: "1072808760 1577896594"
MODULE: rdpcs_pipe_apb
ANNOTATION: " tied to 0 "
Toggle rdpcs_pipe_apb_debug_data [31:11] "net rdpcs_pipe_apb_debug_data[31:0]"
CHECKSUM: "1072808760 2643556665"
MODULE: rdpcs_pipe_apb
ANNOTATION: " pready = gen_ack, gen_ack only gets generated in ACCESS state. Impossible to cover as pready = idp_apb_pready && tx_state == 2'b10 "
Condition 6 "3405309556" "(pready && (tx_state == 2'b10)) 1 -1" (2 "10")
MODULE: rdpcs_pipe_apb
Fsm tx_state "0"
ANNOTATION: " Only happens if wrtig or rtrig happens at the same time as pready in access state which is not possible as wtrig or rtrig asserts only when phyreg_ack got generated to unload a new entry from cmd_fifo. phyreg_ack gets generated in IDLE states as phyreg_ack is generated when \"pready & state == ACCESS\". "
Transition ACCESS->SETUP "2->0"
ANNOTATION: " will not get covered unless there is a reset at this state "
Transition SETUP->IDLE "0->1"

