//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Tue Apr  6 16:37:40 2021
// ExclMode: default
//==================================================
CHECKSUM: "780640977 1708994334"
MODULE: rdpcs_1to2_packer
ANNOTATION_BEGIN: " tied to 0 "
Toggle rdpcs_1to2_packer_debug [4:1] "net rdpcs_1to2_packer_debug[31:0]"
Toggle rdpcs_1to2_packer_debug [9:7] "net rdpcs_1to2_packer_debug[31:0]"
Toggle rdpcs_1to2_packer_debug [31:30] "net rdpcs_1to2_packer_debug[31:0]"
ANNOTATION_END
