//==================================================
// This file contains the Excluded objects
// Generated By User: winnimui
// Format Version: 2
// Date: Mon Apr  3 15:26:44 2023
// ExclMode: default
//==================================================
CHECKSUM: "2779972168 4241272726"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.udpcs_ocla_clk_antiglitch
ANNOTATION: " rf_symclk_enable is 0 on the rest, so this condition cannot be met "
Condition 2 "2273493789" "((symclk_reset == 1'b1) || (rf_symclk_enable == 1'b0)) 1 -1" (3 "10")
CHECKSUM: "2779972168 3274068257"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.udpcs_ocla_clk_antiglitch
ANNOTATION: " default is 1, 1->0 is good enough for testing "
Toggle 0to1 SYMCLK_GATE_DISABLE_symclk "net SYMCLK_GATE_DISABLE_symclk"
ANNOTATION: " default is 1, 1->0 is good enough for testing "
Toggle 0to1 irf_SYMCLK_GATE_DISABLE "net irf_SYMCLK_GATE_DISABLE"
CHECKSUM: "4101901131 3636276941"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg
ANNOTATION: " default is 1, 1->0 is good enough for testing "
Toggle 0to1 irf_RDPCS_OCLACLK_GATE_DIS "net irf_RDPCS_OCLACLK_GATE_DIS"
ANNOTATION: " default is 0, 0->1 is enough testing "
Toggle 1to0 irf_RDPCS_PHY_CLOCKS_GATE_DIS "net irf_RDPCS_PHY_CLOCKS_GATE_DIS"
ANNOTATION: " default is 0, 0->1 is enough testing "
Toggle 1to0 RDPCS_PHY_CLOCKS_GATE_DIS_phyd18clk "net RDPCS_PHY_CLOCKS_GATE_DIS_phyd18clk"
ANNOTATION: " default is 0, 0->1 is enough testing "
Toggle 1to0 RDPCS_PHY_CLOCKS_GATE_DIS_phyd32clk "net RDPCS_PHY_CLOCKS_GATE_DIS_phyd32clk"
ANNOTATION: " default is 0, 0->1 is enough testing "
Toggle 1to0 RDPCS_PHY_CLOCKS_GATE_DIS_phyclk "net RDPCS_PHY_CLOCKS_GATE_DIS_phyclk"
ANNOTATION: " Toggle 0->1 is enough "
Toggle 1to0 irf_RDPCS_OCLACLK_EN "net irf_RDPCS_OCLACLK_EN"
ANNOTATION: " Toggle 0->1 is enough "
Toggle 1to0 ocla_clk_clock_on "net ocla_clk_clock_on"
ANNOTATION: " Toggle 0->1 is enough "
Toggle 1to0 ocla_clk_mux_sel "net ocla_clk_mux_sel"
CHECKSUM: "2439288616 3676833729"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uPHYD32CLK_RDPCS_MUX.uaticlk_mux2
Toggle 0to1 clk_i [0] "net clk_i[1:0]"
Toggle 1to0 clk_i [0] "net clk_i[1:0]"
CHECKSUM: "2439288616 3676833729"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uPHYD18CLK_RDPCS_MUX.uaticlk_mux2
Toggle 0to1 clk_i [0] "net clk_i[1:0]"
Toggle 1to0 clk_i [0] "net clk_i[1:0]"
CHECKSUM: "2439288616 3676833729"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uPHYCLK_RDPCS_MUX.uaticlk_mux2
Toggle 0to1 clk_i [0] "net clk_i[1:0]"
Toggle 1to0 clk_i [0] "net clk_i[1:0]"
CHECKSUM: "2159980380 883975564"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uPHYD32CLK_RDPCS_MUX
Toggle 1to0 I0 "net I0"
Toggle 0to1 I0 "net I0"
CHECKSUM: "2159980380 883975564"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uPHYD18CLK_RDPCS_MUX
Toggle 1to0 I0 "net I0"
Toggle 0to1 I0 "net I0"
CHECKSUM: "2159980380 883975564"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uPHYCLK_RDPCS_MUX
Toggle 1to0 I0 "net I0"
Toggle 0to1 I0 "net I0"
CHECKSUM: "2224341301 4279574096"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uTX_CLK_RDPCS_TX0_GATER
Toggle 1to0 pm_enb "net pm_enb"
Toggle 0to1 pm_enb "net pm_enb"
CHECKSUM: "2224341301 4279574096"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uOCLACLK_GATER
Toggle 1to0 pm_enb "net pm_enb"
Toggle 0to1 pm_enb "net pm_enb"
CHECKSUM: "2224341301 4279574096"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uTX_CLK_RDPCS_TX1_GATER
Toggle 1to0 pm_enb "net pm_enb"
Toggle 0to1 pm_enb "net pm_enb"
CHECKSUM: "2224341301 4279574096"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uTX_CLK_RDPCS_TX2_GATER
Toggle 1to0 pm_enb "net pm_enb"
Toggle 0to1 pm_enb "net pm_enb"
CHECKSUM: "2224341301 4279574096"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uTX_CLK_RDPCS_TX3_GATER
Toggle 1to0 pm_enb "net pm_enb"
Toggle 0to1 pm_enb "net pm_enb"
CHECKSUM: "2224341301 4279574096"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uTX_CLK_RDPCS_GATER
Toggle 1to0 pm_enb "net pm_enb"
Toggle 0to1 pm_enb "net pm_enb"
CHECKSUM: "2224341301 4279574096"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cg.uSRAMCLK_GATER
Toggle 1to0 pm_enb "net pm_enb"
Toggle 0to1 pm_enb "net pm_enb"

CHECKSUM: "4276213954 765189495"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.uDPCS_DC_phyd32clk_antiglitch
ANNOTATION: "correct, tie '1', cann't cover"
Toggle SYMCLK_GATE_DISABLE_symclk "net SYMCLK_GATE_DISABLE_symclk"
CHECKSUM: "4276213954 765189495"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.uDPCS_DC_phyd18clk_antiglitch
ANNOTATION: "correct, tie '1', cann't cover"
Toggle SYMCLK_GATE_DISABLE_symclk "net SYMCLK_GATE_DISABLE_symclk"
CHECKSUM: "2779972168 3274068257"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.udpcs_tx_clk_rdpcs_antiglitch
ANNOTATION: "correct, tie '1', cann't cover"
Toggle SYMCLK_GATE_DISABLE_symclk "net SYMCLK_GATE_DISABLE_symclk"
CHECKSUM: "2779972168 3274068257"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.udpcs_sram_clk_antiglitch
ANNOTATION: "correct, tie '1', cann't cover"
Toggle SYMCLK_GATE_DISABLE_symclk "net SYMCLK_GATE_DISABLE_symclk"
CHECKSUM: "2779972168 3274068257"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.udpcs_rom_clk_antiglitch
ANNOTATION: "correct, tie '1', cann't cover"
Toggle SYMCLK_GATE_DISABLE_symclk "net SYMCLK_GATE_DISABLE_symclk"
CHECKSUM: "2779972168 3274068257"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.uDPCS_DC_phyclk_antiglitch
ANNOTATION: "correct, tie '1', cann't cover"
Toggle SYMCLK_GATE_DISABLE_symclk "net SYMCLK_GATE_DISABLE_symclk"
CHECKSUM: "2779972168 3766200989"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.udpcs_tx_clk_rdpcs_antiglitch
ANNOTATION: "correct, disable tie '1'"
Condition 14 "629760045" "(((~symclk_clk_src_sel_change)) & (symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk)) 1 -1" (2 "10")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "1309056787" "(symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk) 1 -1" (1 "00")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "1309056787" "(symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk) 1 -1" (3 "10")
CHECKSUM: "2779972168 3766200989"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.udpcs_sram_clk_antiglitch
ANNOTATION: "correct, disable tie '1'"
Condition 14 "629760045" "(((~symclk_clk_src_sel_change)) & (symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk)) 1 -1" (2 "10")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "1309056787" "(symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk) 1 -1" (1 "00")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "1309056787" "(symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk) 1 -1" (3 "10")
CHECKSUM: "2779972168 3766200989"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.udpcs_rom_clk_antiglitch
ANNOTATION: "correct, disable tie '1'"
Condition 14 "629760045" "(((~symclk_clk_src_sel_change)) & (symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk)) 1 -1" (2 "10")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "1309056787" "(symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk) 1 -1" (1 "00")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "1309056787" "(symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk) 1 -1" (3 "10")
CHECKSUM: "2779972168 3766200989"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.uDPCS_DC_phyclk_antiglitch
ANNOTATION: "reset cond, symclk_reset covered, can waive"
Condition 10 "2273493789" "((symclk_reset == 1'b1) || (rf_symclk_enable == 1'b0)) 1 -1" (3 "10")
ANNOTATION: "correct, disable tie '1'"
Condition 14 "629760045" "(((~symclk_clk_src_sel_change)) & (symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk)) 1 -1" (2 "10")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "1309056787" "(symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk) 1 -1" (1 "00")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "1309056787" "(symclk_srcsel_reg | SYMCLK_GATE_DISABLE_symclk) 1 -1" (3 "10")
CHECKSUM: "4276213954 3815275007"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.uDPCS_DC_phyd32clk_antiglitch
ANNOTATION: "correct, disable tie '1'"
Condition 14 "3536368172" "(((~symclk_clk_src_sel_change)) & (symclk_srcsel_reg[1] | SYMCLK_GATE_DISABLE_symclk)) 1 -1" (2 "10")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "2724287440" "(symclk_srcsel_reg[1] | SYMCLK_GATE_DISABLE_symclk) 1 -1" (1 "00")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "2724287440" "(symclk_srcsel_reg[1] | SYMCLK_GATE_DISABLE_symclk) 1 -1" (3 "10")
ANNOTATION: "reset cond, symclk_reset covered, can waive"
Condition 10 "2273493789" "((symclk_reset == 1'b1) || (rf_symclk_enable == 1'b0)) 1 -1" (3 "10")
CHECKSUM: "4276213954 3815275007"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_pipe_dc0.urdpcs_pipe_dc0.urdpcs_cg.uDPCS_DC_phyd18clk_antiglitch
ANNOTATION: "reset cond, symclk_reset covered, can waive"
Condition 10 "2273493789" "((symclk_reset == 1'b1) || (rf_symclk_enable == 1'b0)) 1 -1" (3 "10")
ANNOTATION: "correct, disable tie '1'"
Condition 14 "3536368172" "(((~symclk_clk_src_sel_change)) & (symclk_srcsel_reg[1] | SYMCLK_GATE_DISABLE_symclk)) 1 -1" (2 "10")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "2724287440" "(symclk_srcsel_reg[1] | SYMCLK_GATE_DISABLE_symclk) 1 -1" (1 "00")
ANNOTATION: "correct, disable tie '1'"
Condition 15 "2724287440" "(symclk_srcsel_reg[1] | SYMCLK_GATE_DISABLE_symclk) 1 -1" (3 "10")
