//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Tue Sep 29 10:27:59 2020
// ExclMode: default
//==================================================
CHECKSUM: "2003592491 1433049449"
MODULE: rdpcs_pipe_msg
Toggle lane1_m2p_addr [12] "net lane1_m2p_addr[12:0]"
ANNOTATION_BEGIN: " tied to 0 "
Toggle lane0_m2p_addr [12] "net lane0_m2p_addr[12:0]"
Toggle lane0_m2p_data [9] "net lane0_m2p_data[9:0]"
Toggle rdpcs_pipe_msg_debug_data [31:27] "net rdpcs_pipe_msg_debug_data[31:0]"
Toggle lane0_m2p_addr_inc [12] "net lane0_m2p_addr_inc[12:0]"
ANNOTATION_END
ANNOTATION_BEGIN: " tied to 1 "
Toggle lane1_m2p_data [9] "net lane1_m2p_data[9:0]"
Toggle lane1_m2p_addr_inc [12] "net lane1_m2p_addr_inc[12:0]"
ANNOTATION_END
CHECKSUM: "2003592491 85815111"
MODULE: rdpcs_pipe_msg
Fsm state "85815111"
ANNOTATION_BEGIN: " Happens only if reset asserts in this state "
Transition SND_RD_ADDR1->IDLE "11->0"
Transition SND_RD_CMD->IDLE "10->0"
Transition SND_WR_ADDR1->IDLE "3->0"
Transition SND_WR_CMD->IDLE "1->0"
Transition WAIT_RD_ACK->IDLE "9->0"
ANNOTATION_END
