//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Fri Dec 17 11:48:58 2021
// ExclMode: default
//==================================================
CHECKSUM: "1510543664 1839836832"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcs_cr_intf
ANNOTATION_BEGIN: " tied to 0 "
Toggle cr_intf_debug_data0 [7:0] "net cr_intf_debug_data0[31:0]"
Toggle cr_intf_debug_data0 [31] "net cr_intf_debug_data0[31:0]"
ANNOTATION_END
