//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Fri Dec 17 12:55:38 2021
// ExclMode: default
//==================================================
CHECKSUM: "2278841250 2943838469"
INSTANCE: tb.gpu0.chip0.core.udcnc.udpcsc.rdpcs_tx_dc0.urdpcs_tx_dc0.urdpcstx_reg_dec.urdpcs_cmd_fifo
ANNOTATION_BEGIN: " unused address bits as we have only 54 registers in rdpcs_tx "
Toggle SLAVE_DEC_addr [15:6] "net SLAVE_DEC_addr[15:0]"
Toggle rdpcs_reg_addr [15:6] "net rdpcs_reg_addr[15:0]"
Toggle rdpcs_reg_addr_out [15:6] "net rdpcs_reg_addr_out[15:0]"
ANNOTATION_END
CHECKSUM: "2278841250 2943838469"
//INSTANCE: tb.gpu0.chip0.core.udpcssys_tb_usb.dpcssys_tb_c20_usb0.rdpcs_pipe_usb.urdpcs_pipe_usb0.urdpcspipe_reg_dec.urdpcs_cmd_fifo
MODULE: rdpcs_cmd_fifo
ANNOTATION_BEGIN: " unused address bits as we have only 43 registers in rdpcs_pipe "
Toggle SLAVE_DEC_addr [15:6] "net SLAVE_DEC_addr[15:0]"
Toggle rdpcs_reg_addr [15:7] "net rdpcs_reg_addr[15:0]"
Toggle rdpcs_reg_addr_out [15:6] "net rdpcs_reg_addr_out[15:0]"
ANNOTATION_END
