//==================================================
// This file contains the Excluded objects
// Generated By User: aradan
// Format Version: 2
// Date: Thu Oct 15 11:00:21 2020
// ExclMode: default
//==================================================
CHECKSUM: "3238770646 2967349506"
MODULE: rdpcs_pipe_checker
ANNOTATION: " impossible condition, wtrig_data_dly is delayed version of wtrig_data "
Condition 6 "3288570210" "(((~wtrig_data_dly)) && iwtrig_data) 1 -1" (1 "01")
ANNOTATION: " impossible condition, rtrig_data_dly is delayed version of rtrig_data "
Condition 7 "4114727016" "(((~rtrig_data_dly)) && irtrig_data) 1 -1" (1 "01")
ANNOTATION: " Will not get covered. when fake_ack gets generated apb FSM goes back to IDLE states. PREADY signals from PHY only gets accepted as true_ack when apb FSM is in ACESS state. "
Condition 9 "758132979" "(((~block_ack)) && true_ack) 1 -1" (1 "01")
